const vehicleData = [
  {
    id: 1,
    alias: "Tony's Car",
    vehicleMake: 'GMC',
    model: 'Terrain',
    year: 2018,
    color: 'Black',
    plates: 'ABC2308',
    favorite: true,
  },
  {
    id: 2,
    alias: 'My Car',
    vehicleMake: 'Mazda',
    model: '3',
    year: 2019,
    color: 'Red',
    plates: 'DEF2308',
    favorite: false,
  },
  {
    id: 3,
    alias: "Mom's Car",
    vehicle: 'Hyndai Elantra',
    vehicleMake: 'Hyndai',
    model: 'Elantra',
    year: 2017,
    color: 'White',
    plates: 'GHI2308',
    favorite: false,
  },
  {
    id: 4,
    alias: "Mario's Car",
    vehicle: 'Honda Civic',
    vehicleMake: 'Honda',
    model: 'Civic',
    year: 2016,
    color: 'Blue',
    plates: 'JKL2308',
    favorite: false,
  },
];

export default vehicleData;